-- Migration: Quality Gate — adds new quote statuses and clarification columns
-- Phase 4: Quality Gate with clarification flow

-- Add new quote status values
ALTER TYPE quote_status ADD VALUE IF NOT EXISTS 'pending_review' AFTER 'generating';
ALTER TYPE quote_status ADD VALUE IF NOT EXISTS 'awaiting_clarification' AFTER 'pending_review';

-- Add quality gate and clarification columns to quotes
ALTER TABLE quotes ADD COLUMN IF NOT EXISTS clarification_questions_json JSONB;
ALTER TABLE quotes ADD COLUMN IF NOT EXISTS clarification_answers_json JSONB;
ALTER TABLE quotes ADD COLUMN IF NOT EXISTS clarification_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE quotes ADD COLUMN IF NOT EXISTS quality_gate_json JSONB;

COMMENT ON COLUMN quotes.clarification_questions_json IS 'Questions generated by quality gate for customer clarification';
COMMENT ON COLUMN quotes.clarification_answers_json IS 'Customer answers to clarification questions';
COMMENT ON COLUMN quotes.clarification_count IS 'Number of clarification rounds (capped at 1)';
COMMENT ON COLUMN quotes.quality_gate_json IS 'Quality gate evaluation result: action, questions, review reason';
